name: Bug report
description: File a bug report for rules_fortran
labels: ["bug"]
assignees:
  - miinso
body:
  - type: markdown
    attributes:
      value: >
        **Attention:** if this is a _question_ about how to use rules_fortran or Fortran with Bazel,
        please start a discussion in [GitHub Discussions](https://github.com/miinso/fortran-go-brrr/discussions)
        or ask on [Bazel Slack](https://slack.bazel.build/) instead!
  - type: textarea
    id: desc
    attributes:
      label: >
        Description of the bug:
  - type: dropdown
    id: component
    attributes:
      label: Which component does this issue belong to?
      description: Help us triage this issue faster. Select all that apply.
      multiple: true
      options:
        - Compilation
        - Linking
        - Module Dependencies
        - Toolchain Configuration
        - C/Fortran Interop
        - Provider Design (CcInfo, FortranInfo)
        - Testing
        - Documentation
        - Examples
        - Performance
  - type: textarea
    id: repro
    attributes:
      label: >
        What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if
        possible.
  - type: dropdown
    id: platform
    attributes:
      label: Which platform(s) does this affect?
      description: Select all that apply
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - All
        - Platform-agnostic
  - type: input
    id: bazel-version
    attributes:
      label: >
        What is the output of `bazel info release`?
  - type: input
    id: flang-version
    attributes:
      label: >
        Which version of flang are you using? (e.g., v21.1.3)
  - type: textarea
    id: module-bazel
    attributes:
      label: >
        Please share your MODULE.bazel or WORKSPACE configuration for rules_fortran
      description: >
        Show how you're loading rules_fortran (version, configuration, etc.)
      render: python
  - type: textarea
    id: relevant-info
    attributes:
      label: Have you found anything relevant by searching the web?
      description: >
        Places to look:

         * StackOverflow: http://stackoverflow.com/questions/tagged/bazel
         * GitHub issues: https://github.com/bazelbuild/bazel/issues
         * Email threads on https://groups.google.com/forum/#!forum/bazel-discuss
  - type: textarea
    id: extras
    attributes:
      label: Any other information, logs, or outputs that you want to share?
