! LAPACK Example: Solve a linear system Ax = b using Cholesky decomposition
! Using DPOTRF (Cholesky factorization) and DPOTRS (solve using factorization)
! A must be symmetric positive definite: A = LL^T
!
! Test problem generated by MATLAB with known solution x = [1, 2, 3, 4, 5]^T

program main
    implicit none
    integer, parameter :: N = 5, NRHS = 1
    integer :: INFO, i
    double precision :: A(N,N), B(N,NRHS), x_true(N), max_error
    
    ! Initialize matrix A (column-major, generated by MATLAB)
    ! Symmetric positive definite matrix
    A(1,1) =   0.2897064891368453d0
    A(2,1) =  -0.4667824132897773d0
    A(3,1) =  -0.5253187543265192d0
    A(4,1) =  -0.1815982431468881d0
    A(5,1) =   0.5361415650827721d0
    A(1,2) =  -0.4667824132897773d0
    A(2,2) =   2.4354615712348719d0
    A(3,2) =  -0.3438566640349989d0
    A(4,2) =   0.0634643390205203d0
    A(5,2) =  -1.8436511349616569d0
    A(1,3) =  -0.5253187543265192d0
    A(2,3) =  -0.3438566640349989d0
    A(3,3) =   5.0953578599419513d0
    A(4,3) =   0.2663050688351638d0
    A(5,3) =  -2.2972572108777007d0
    A(1,4) =  -0.1815982431468881d0
    A(2,4) =   0.0634643390205203d0
    A(3,4) =   0.2663050688351638d0
    A(4,4) =   0.5972905775101480d0
    A(5,4) =  -0.2674138702334130d0
    A(1,5) =   0.5361415650827721d0
    A(2,5) =  -1.8436511349616569d0
    A(3,5) =  -2.2972572108777007d0
    A(4,5) =  -0.2674138702334130d0
    A(5,5) =   3.8903080413667199d0
    
    ! Initialize right-hand side B (generated by MATLAB: b = A*x_true)
    B(1,1) =  -0.2654997475959586d0
    B(2,1) =  -5.5918275816512333d0
    B(3,1) =   3.6519757183814878d0
    B(4,1) =   1.7963386002731709d0
    B(5,1) =   8.3389523884263035d0
    
    ! True solution (known from MATLAB)
    x_true(1) =   1.0000000000000000d0
    x_true(2) =   2.0000000000000000d0
    x_true(3) =   3.0000000000000000d0
    x_true(4) =   4.0000000000000000d0
    x_true(5) =   5.0000000000000000d0
    
    ! Compute Cholesky factorization A = LL^T (lower triangular)
    call DPOTRF('L', N, A, N, INFO)
    
    if (INFO /= 0) then
        print *, "ERROR: DPOTRF failed with INFO =", INFO
        stop 1
    end if
    
    ! Solve system using Cholesky factorization
    call DPOTRS('L', N, NRHS, A, N, B, N, INFO)
    
    if (INFO /= 0) then
        print *, "ERROR: DPOTRS failed with INFO =", INFO
        stop 1
    end if
    
    ! Check solution
    print *, "Solution:"
    do i = 1, N
        print '(A,I1,A,F15.10,A,F15.10,A)', "  x(", i, ") = ", B(i,1), "  (expected: ", x_true(i), ")"
    end do
    
    max_error = maxval(abs(B(:,1) - x_true))
    print '(A,ES12.4)', "Max error: ", max_error
    
    if (max_error > 1.0d-6) stop 1
    
end program main
