! LAPACK Example: Solve a linear system Ax = b
! Using DGESV (Double precision General SolVe)
!
! Test problem generated by MATLAB with known solution x = [1, 2, 3, 4, 5]^T

program main
    implicit none
    integer, parameter :: N = 5, NRHS = 1
    integer :: INFO, IPIV(N), i
    double precision :: A(N,N), B(N,NRHS), x_true(N), max_error
    
    ! Initialize matrix A (column-major, generated by MATLAB)
    ! Symmetric positive definite matrix with condition number ~10
    A(1,1) =   3.0735576780535467d0
    A(2,1) =  -0.3556336795666404d0
    A(3,1) =  -1.9683135423320477d0
    A(4,1) =  -0.5632738053896288d0
    A(5,1) =   1.3137391956258364d0
    A(1,2) =  -0.3556336795666402d0
    A(2,2) =   5.0629585069022420d0
    A(3,2) =   1.2725310062230402d0
    A(4,2) =  -0.0202957325072488d0
    A(5,2) =  -2.8662131876165229d0
    A(1,3) =  -1.9683135423320473d0
    A(2,3) =   1.2725310062230408d0
    A(3,3) =   5.7701749654939372d0
    A(4,3) =   0.9155470887737265d0
    A(5,3) =  -1.6628376410776389d0
    A(1,4) =  -0.5632738053896288d0
    A(2,4) =  -0.0202957325072485d0
    A(3,4) =   0.9155470887737265d0
    A(4,4) =   2.3989684064132692d0
    A(5,4) =  -1.3908071865298743d0
    A(1,5) =   1.3137391956258364d0
    A(2,5) =  -2.8662131876165229d0
    A(3,5) =  -1.6628376410776389d0
    A(4,5) =  -1.3908071865298743d0
    A(5,5) =   4.6943404431370048d0
    
    ! Initialize right-hand side B (generated by MATLAB: b = A*x_true)
    B(1,1) =   0.7729504484947913d0
    B(2,1) =  -0.8243725152046419d0
    B(3,1) =  13.2352735163025557d0
    B(4,1) =   4.7846136889207571d0
    B(5,1) =   8.5012733667254015d0
    
    ! True solution (known from MATLAB)
    x_true(1) =   1.0000000000000000d0
    x_true(2) =   2.0000000000000000d0
    x_true(3) =   3.0000000000000000d0
    x_true(4) =   4.0000000000000000d0
    x_true(5) =   5.0000000000000000d0
    
    ! Solve system
    call DGESV(N, NRHS, A, N, IPIV, B, N, INFO)
    
    if (INFO /= 0) then
        print *, "ERROR: DGESV failed with INFO =", INFO
        stop 1
    end if
    
    ! Check solution
    print *, "Solution:"
    do i = 1, N
        print '(A,I1,A,F15.10,A,F15.10,A)', "  x(", i, ") = ", B(i,1), "  (expected: ", x_true(i), ")"
    end do
    
    max_error = maxval(abs(B(:,1) - x_true))
    print '(A,ES12.4)', "Max error: ", max_error
    
    if (max_error > 1.0d-6) stop 1
    
end program main
